<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>XTMF2.RunServer</RootNamespace>
    <ApplicationIcon />
    <OutputTypeEx>exe</OutputTypeEx>
    <StartupObject></StartupObject>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>..\..\..\XTMF2-Dev\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\src\XTMF2.Run\bin\$(Configuration)\$(TargetFramework)\XTMF2.Run.deps.json" Link="XTMF2.Run.deps.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\src\XTMF2.Run\bin\$(Configuration)\$(TargetFramework)\XTMF2.Run.runtimeconfig.json" Link="XTMF2.Run.runtimeconfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XTMF2.Run\XTMF2.Run.csproj" />
    <ProjectReference Include="..\XTMF2\XTMF2.csproj" />
    <ProjectReference Include="..\XTMF2.Interfaces\XTMF2.Interfaces.csproj" />
  </ItemGroup>

</Project>
