<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.14" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.14" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.14" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.14" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1-build.4" />
    <PackageReference Include="Dock.Avalonia" Version="11.3.11.22" />
    <PackageReference Include="Dock.Model.Avalonia" Version="11.3.11.22" />
    <PackageReference Include="Dock.Avalonia.Themes.Fluent" Version="11.3.11.22" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings.fr.resx">
      <DependentUpon>Strings.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings.es.resx">
      <DependentUpon>Strings.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>    <AvaloniaResource Include="Resources\XTMF_icon.png"/>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>XTMF2.GUI.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>    
    <ProjectReference Include="..\XTMF2\XTMF2.csproj" />
    <ProjectReference Include="..\XTMF2.Interfaces\XTMF2.Interfaces.csproj" />
    <ProjectReference Include="..\XTMF2.Client\XTMF2.RunServer.csproj" />
    <ProjectReference Include="..\XTMF2.Run\XTMF2.Run.csproj" />
  </ItemGroup>
</Project>
